### ISSUE TITLE
Can't get the my webcam to take sample pictures for the opencv recognizer python app. 

### ISSUE THREAD

**Issue by macquaisie** [ragundez/PyData#2]
I am get errors anytime i run the start recon script.
![img_20160724_102852 1](https://cloud.githubusercontent.com/assets/20623762/17083502/d9373702-519a-11e6-9df5-799a3a3e74bf.jpg)
![img_20160724_103323 1](https://cloud.githubusercontent.com/assets/20623762/17083504/f1bea74c-519a-11e6-91e8-803d260a7684.jpg)

**Comment by rragundez** [comment]
@macquaisie So it appears that the camera if recognize is not capturing any frame. Since the image is None. To check this in the anaconda console do:

``` python
>>> import cv2
>>> video = cv2.VideoCapture(0)
>>> ret, frame = video.read()
>>> print ret
>>> print type(frame)
```

And tell me what it outputs.

**Comment by macquaisie** [comment]
@rragundez This is what I got please.

> > > import cv2
> > > video = cv2.VideoCapture(0)
> > > ret, frame = video.read()
> > > print ret
> > > True
> > > print type(frame)
> > > <type 'numpy.ndarray'>

**Comment by globsecure** [comment]
```
Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> vodeo = cv2.VideoCapture(0)
>>> ret, frame = video.read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'video' is not defined
>>> ret, frame = vodeo.read()
>>> print ret
True
>>> print type(frame)
<type 'numpy.ndarray'>
>>> 

```

**Comment by rragundez** [comment]
hi @globsecure it seems that it is capturing the image correctly

**Comment by AurangzaibKhan** [comment]
i want to run this code in raspberry pi.... so which tool I should used to run this project.???

**Comment by rragundez** [comment]
Hi @AurangzaibKhan you should use Python, OpenCV and the packages listed in `requirements.txt` of course (which you install by `pip install -r requirements.txt`).
