### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MinDistancePredictCollector'

### ISSUE THREAD

**Issue by jamescfli** [ragundez/PyData#6]
Hi @rragundez,

I have tried your code "04_Recognize_Faces_in_a_Live_VIdeo_Feed.ipynb" and got the following error:

> AttributeError: 'module' object has no attribute 'MinDistancePredictCollector'

and it turns out cv2.face only has limited functions

    >>> help(cv2.face)
    Help on module cv2.face in cv2:

    NAME
        cv2.face

    FILE
        (built-in)

    FUNCTIONS
        StandardCollector_create(...)
            StandardCollector_create([, threshold]) -> retval
    
        createBIF(...)
            createBIF([, num_bands[, num_rotations]]) -> retval
    
        createEigenFaceRecognizer(...)
            createEigenFaceRecognizer([, num_components[, threshold]]) -> retval
    
        createFisherFaceRecognizer(...)
            createFisherFaceRecognizer([, num_components[, threshold]]) -> retval
    
        createLBPHFaceRecognizer(...)
            createLBPHFaceRecognizer([, radius[, neighbors[, grid_x[, grid_y[, threshold]]]]]) -> retval

Is there something different in my OpenCV (version '3.1.0-dev') from the one you used? Thanks for the help in advance.

Cheers,
James

**Comment by rragundez** [comment]
Hi @jamescfli I am currently not maintaining these notebooks, and at the moment I cannot run them but it appears they change the collector. Probably acts in the same way, have you tried to change the line 
```python
collector = cv2.face.MinDistancePredictCollector()
```
to
```python
collector = cv2.face.StandardCollector_create()
```

**Comment by jamescfli** [comment]
Thanks @rragundez  Problem solved by the following code:

    if cv2.__version__ >= "3.1.0":
        collector = cv2.face.StandardCollector_create()
        rec_lbph.predict_collect(face, collector)
        conf = collector.getMinDist()
        pred = collector.getMinLabel()
    else:     # older version
        pred, conf = rec_lbph.predict(face)
