### ISSUE TITLE
Can you explain this error??

### ISSUE THREAD

**Issue by danielpanda** [ragundez/PyData#7]
excuse me sir,
why i got  this error sir? 

![image](https://user-images.githubusercontent.com/29721735/28901675-24cf9668-7824-11e7-959c-73430ad4c384.png)

please help me , i'm testing on raspberry pi 3
:( @rragundez

**Comment by rragundez** [comment]
This code is not longer maintained.
The image is None so `len()` does not work. Probably the camera is not taking pictures.
