### ISSUE TITLE
Threshold LBPH?

### ISSUE THREAD

**Issue by stepenik** [ragundez/PyData#8]
In start_face_recon_app.py you put

```
recognizer = cv2.face.createLBPHFaceRecognizer()
threshold = 105 
```

But in 04_Recognize_Faces_in_a_Live_VIdeo_Feed.ipynb you put

```
rec_lbph = cv2.face.createLBPHFaceRecognizer()
threshold = 140
```

Which threshold is better for LBPH 105 or 140?

**Comment by rragundez** [comment]
It depends on your environment, and specifics of the camera. I can't really say what is the best. Try to find out by playing with the value.

**Comment by stepenik** [comment]
Thanks. When you run app which project works better for you start_face_recon_app.py or 04_Recognize_Faces_in_a_Live_VIdeo_Feed.ipynb.
I think in demo https://www.youtube.com/watch?v=MDaZtJPv3Ik you run 04_Recognize_Faces_in_a_Live_VIdeo_Feed.ipynb project.

**Comment by rragundez** [comment]
The best for an application is to use the .py file. The .ipynb is a notebook for demonstration purposes. 
I am building a better API in a project called `I-Know-you` (https://github.com/rragundez/I-know-you) I will released it in a few months I think.

**Comment by stepenik** [comment]
Ok this new project` I-know-you` will be will be released before of end year?

**Comment by rragundez** [comment]
not sure, depends on how much time I have, but it is possible.
